import { axios, localhost } from '../other/utils/axios/axios'

export const getCodeForRegister = (body) => axios.post(`${localhost}/getCodeForRegister`, body)
export const getNewCode = (newCode) => axios.post(`${localhost}/getNewCode?newCode=${newCode}`)
export const verifycodeRegister = (body) => axios.post(`${localhost}/verifycodeRegister`, body)
export const login = (body) => axios.post(`${localhost}/login`, body)
export const verifyCodeLoginForAdmin = (body) => axios.post(`${localhost}/verifyCodeLoginForAdmin`, body)
export const getCodeForgetPass = (newCode,body) => axios.post(`${localhost}/getCodeForgetPass?newCode=${newCode}`, body)
export const verifycodeForgetPass = (body) => axios.post(`${localhost}/verifycodeForgetPass`, body)
export const resetPassword = (body) => axios.post(`${localhost}/resetPassword`, body)
export const resetSpecification = (body) => axios.post(`${localhost}/resetSpecification`, body)
export const verifycodeResetSpecification = (body) => axios.post(`${localhost}/verifycodeResetSpecification`, body)
export const getUserSpecification = () => axios.get(`${localhost}/getUserSpecification`)
export const sendImageProfile = (body) => axios.postData(`${localhost}/sendImageProfile`, body)
export const getImageProfile = () => axios.get(`${localhost}/getImageProfile`)
export const sendProposal = (body) => axios.post(`${localhost}/sendProposal`,body)
export const getLastPayment = () => axios.get(`${localhost}/getLastPayment`)
export const getAnswersTicket = (id) => axios.get(`${localhost}/getAnswersTicket/${id}`)
export const sendTicketAnswer = (body, id) => axios.postData(`${localhost}/sendTicketAnswer/${id}`, body)
export const sendNewTicket = (body) => axios.postData(`${localhost}/sendNewTicket`, body)
export const ticketBox = () => axios.get(`${localhost}/ticketBox`)
export const deleteAnswerTicket = (id, ticketid) => axios.delete(`${localhost}/deleteAnswerTicket/${id}?ticketid=${ticketid}`)
export const deleteTicket = (id) => axios.delete(`${localhost}/deleteTicket/${id}`)
export const editAnswerTicket = (body, id, ticketid) => axios.putData(`${localhost}/editAnswerTicket/${id}?ticketid=${ticketid}`, body)
export const getSingleAnswerTicket = (id, ticketid) => axios.get(`${localhost}/getSingleAnswerTicket/${id}?ticketid=${ticketid}`)
export const ticketSeen = (id) => axios.post(`${localhost}/ticketSeen/${id}`)
export const getTicketSeen = () => axios.get(`${localhost}/getTicketSeen`)

export const removeSavedProduct = async (id) => axios.delete(`${localhost}/removeSavedProduct/${id}`)
export const savedProduct = async (id) => axios.post(`${localhost}/savedProduct/${id}`)
export const getSavedProducts = () => axios.get(`${localhost}/getSavedProducts`)
export const getAllProductForSeller = () => axios.get(`${localhost}/getAllProductForSeller`)
